---
title: "Homework 3"
subtitle: "Autumn 2022"
author: "YOUR NAME"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 
### Instructions

- This homework is due in Gradescope on Wednesday Oct 26 by midnight PST.

- Please answer the following questions in the order in which they are posed. 

- Don't forget to knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. 


* * *

1. (Shelley) Below are the last five lines of Shelley's poem *Ozymandias* 

   ```{verbatim}
   "My name is Ozymandias, king of kings:
    Look on my works, ye Mighty, and despair!"
    Nothing beside remains. Round the decay
    Of that colossal wreck, boundless and bare
    The lone and level sands stretch far away 
   ```

   Let $X$ denote the length of a word which is randomly selected from those lines. 

a. Write the P.M.F. of $X$ in tabular form. 
    
b. Make a probability histogram of the distribution in part a.

c. Write the C.D.F. of $X$.


\dotfill

2. (Random walk) Suppose a particle moves 4 steps along the x-axis, starting at 0. At each step, it moves one unit to the right or to the left and is equally  likely to go to the right as it is to the left. 

a. Each possible outcome of this experiment is a 4-tuple. For example, the outcome $(L, L, L, L)$ represents the case when the particle moves one unit to the left at each of the four steps to end up at $x=-4$. The outcome $(R, L, R, L)$ represents the case when the particle moves one unit to the right, then one unit back to the left and so on ending up at $x=0$. How many elements are in the sample space? Be sure to calculate the number and also justify your answer.

b. Let $E$ denote the event that the particle ends up at $x = 0$. Write the outcomes in $E$ and calculate $P(E)$. Be sure to justify your answer.

c. Let $X$ denote the position of the particle after 4 steps. Write its PMF in a tabular format. I have created a partial table for you to fill in. Each row should contain a possible value $x$, the outcomes that give the possible value and the probability. (*Hint: in part b you calculated $P(X = 0)$.*)

\begin{table}[h]
\centering
\begin{tabular}{|c|p{4in}|r|} \hline
$x$ &  outcomes from $S$ & $f(x)$ \\ \hline 
\end{tabular}
\end{table}

d. How would the PMF change if the particle was twice as likely to move to the right as it is to the left? Create a table showing the new PMF. Also clearly state any assumption you need to make in order to re-calculate the probabilities. 

\dotfill

3. (CDF) Suppose the random variable $X$ has the CDF:
\begin{align*}
F(x) &= P(X \leq x), \\
     &= \left\{ \begin{array}{cc}
                      0 & x < 0, \\ \\
            \frac{1}{3} & 0 \leq x < \frac{2}{5}, \\ \\
            \frac{3}{4} & \frac{2}{5} \leq x  < \frac{4}{5}, \\ \\
                      1 & \frac{4}{5} \leq x. \end{array} \right.
\end{align*}

   Find $P(\frac{1}{4} < X < \frac{3}{4})$. Show your work.

\dotfill

4. (Transformation) Suppose $X$ is a discrete uniform random variable on the integers $-n, -n + 1, -n +2, \dots, 0, 1, 2,\dots, n$, that is, 
$$f(x) = P(X = x) = \frac{1}{2n + 1}, \ \ \ x = -n, -n+1, -n+2, \dots,-1, 0,1,2,\dots,n - 1, n.$$

   Write the PMF of $Y = |X|$. Be sure to offer some explanation for your work.
   
