---
title: "Homework 1"
subtitle: "Autumn 2022"
author: "YOUR NAME"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Oct 12 by midnight PST.

- Please answer the following questions in the order in which they are posed. 

- Don't forget to knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. 

* * *


### Exercises 

1. The	crew	of	Apollo	17	consisted	of	two	pilots	and	one	geologist.	Suppose	that	 NASA	had	actually	trained	nine	pilots	and	four	geologists.	How	many	possible	Apollo 17 crews	could	have	been	formed	

    a. 	if	the	two	pilot	positions	have	identical	duties?	
    
    b. if	there	is	a	pilot	and	a	co-pilot?	

2.  For two events $A$ and $B$ with $P(A)=0.5$ and $P(B)=0.8$, what are the largest and smallest possible values for $P(A \cap B)$? 

    *Hint* you will need to use the Bonferroni inequality and also the subset inequality you learned in section.


3.  If $P(A) = \frac{1}{3}$ and $P(B^c)=\frac{1}{4}$, can $A$ and $B$ be disjoint? Support your answer.

4.  Three events $A$, $B$ and $C$ are defined in a sample space. Show that 
$$P(A \cup B \cup C) \leq P(A) + P(B) + P(C).$$ 
   
    *Hint* Define $E = B \cup C$ and apply the union bound to $P(A \cup E)$ first. Then apply the union bound again to $P(E)$. 
    
 