---
title: "Homework 7"
subtitle: "Autumn 2022"
author: "YOUR NAME"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Nov 23 by midnight PST.

- Please answer the following questions in the order in which they are posed. 

- Don't forget to knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. 


* * *


1. A tool-and-die company makes castings for steel stress-monitoring gauges. Their annual profit $Q$ is a function of demand $X$, given by 
$$t(X) = 1 - exp (-2 X).$$
   
   The demand $X$ has the PDF
$$f(x) = 6 e^{-6x} \ \ \ x > 0.$$

a. Interpret the number "6" in the PDF of $X$. This means, describe in your own words what this tells you (in context) about the demand $X$. 

b. Find $E\left[ t(X) \right]$. State any rules you use and show your work clearly. 

2. Suppose the duration of a phone call, $X$, can be described probabilistically by

	 $$P(X > x) = ae^{-\lambda_1 x} + (1-a) e^{-\lambda_2 x}, \ 0 < x < \infty$$
	   
   	where $a$, $\lambda_1$ and $\lambda_2$ are constants, $0 < a < 1, \ \lambda_1, \lambda_2 > 0$. 
   	
a. Write the CDF of $X$ by filling in the question marks in align environment below. Justify your answers below.

   \begin{align*}
   F(x) &= P(X \leq x) \\
   &= \left\{ \begin{array}{cc} 
                   ??? & x < 0\\
                   ??? & x \geq 0.
              \end{array} \right.
    \end{align*}
    
b. Find a PDF, $f(x)$,  for $x$. Show your work. (Don't forget to mention the support)

c. Calculate the expected duration of the call. State the answer in a sentence that shows you understand the meaning of expected value. In other words, we are looking for more than "the expected value is xxx". 
    
d. By how much will the duration of a call typically vary from expected? Calculate the standard deviation $SD(X)$. (\emph{Hint:} begin by finding $$Var\left[X \right] = E\left[X^2 \right] - \mu^2$$ where $\mu$ is your answer to part c. )

   
    \emph{Hint: for parts c and d, you may use the results from Lemma 12.1 without proof but you have to provide complete citations to results you use. This means you cannot just say "from the result we saw in class". This is not how proofs are written. }
   