---
title: "Problem Session 3"
subtitle:  "Discrete Distributions & Binomial"
graphics: yes
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
* * * 
### Instructions

Please answer the following questions in the order in which they are posed. Add a few empty lines below each and write your answers there. Focus on answering in complete sentences. You will also need scratch paper/pen to work out the answers before typing it.

For help with formatting documents in RMarkdown, please consult [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). Another option is to search using Google. 

* * *

### Exercises 
	 
1. Suppose you toss a fair coin 3 times. The sample space for this experiment is shown below:
$$S = \{ HHH, HHT, HTH, HTT, TTT,TTH, THT, THH \}.$$

a. Write the PMF of $X$ defined as the difference between number of heads and number of tails.

b. Give the CDF of $X$.

c. Draw the probability histogram of $X$ in R.

2. Suppose $X$ is a discrete uniform random variable on the integers $-n, -n + 1, -n +2, \dots, 0, 1, 2,\dots, n$, that is, 
$$f(x) = P(X = x) = c, \ \ \ x = -n, -n+1, -n+2, \dots, 1,2,\dots,n.$$

a. What is $c$?
b. What is the PMF of  $$Y = -X? $$

	  
3. Acceptance sampling is a procedure that tests some of the items in a lot or shipment and decides to accept or reject the entire lot based on the results of testing the sample. In a simple case, each item tested is determined to be either defective or acceptable.

    Suppose a purchaser orders 100 items, tests 4 of them and rejects the lot if one or more of those four are found to be defective. 

a. If an item is defective with probability 0.1 (independently of the other items), what is the probability that the purchaser will reject the shipment? (Define the random variable of interest, state its distribution, define the event in random variable notation and then calculate the probability.)

b. Make a graph showing how the probability of rejection varies with the probability of a defective item.